set nocompatible
filetype plugin indent on
"  -------
"  plugins
"  -------
call plug#begin('~/.vim/plugged')
" General vim
source ~/.vim/plug/sonokai.vim
source ~/.vim/plug/fzf.vim
source ~/.vim/plug/airline.vim
" Programming
source ~/.vim/plug/syntastic.vim
source ~/.vim/plug/ale.vim
source ~/.vim/plug/rust-lang.vim
source ~/.vim/plug/clippy.vim

call plug#end()

" -------
" General
" -------

set termguicolors
let &t_ut=''
colorscheme sonokai

set encoding=utf-8
set laststatus=2
set number relativenumber

set tabstop=4
set expandtab
set shiftwidth=4

set cursorline
highlight clear CursorLine
highlight CursorLineNR guifg=#FFD866

highlight ColorColumn guibg=#ffb0c3
call matchadd('ColorColumn', '\%81v', 100)

set listchars=tab:>~,nbsp:_,trail:.
set list

set hidden
set nowrap
set incsearch
set ignorecase
set smartcase

set wildmenu
set wildmode=list:longest
set wildignore=*.docx,*.jpg,*.png,*gif,*.pdf,*.pyc,*.exe,*.flv,*.img,*.xlsx

" -----------
" Keybindings
" -----------

noremap <up> <Nop>
noremap <down> <Nop>
noremap <left> <Nop>
noremap <right> <Nop>

map oo o<esc>
map OO O<esc>

nnoremap <C-o> :Files<CR>
